export const AUTH_DATA_SOURCE = 'AUTH_DATA_SOURCE';
export const AUTH_CREDENTIAL_REPOSITORY = 'AUTH_CREDENTIAL_REPOSITORY';
export const AUTH_ROLE_REPOSITORY = 'AUTH_ROLE_REPOSITORY';
export const VERIFICATION_CODE_REPOSITORY = 'VERIFICATION_CODE_REPOSITORY';
